// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolumeWebService.Persistence;

namespace VolumeWebService.Migrations
{
    [DbContext(typeof(VolumeDBContext))]
    [Migration("20211230235431_vol")]
    partial class vol
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("VolumeWebService.VolumeCalculator.VolumeResult", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("height")
                        .HasColumnType("REAL");

                    b.Property<double>("radius")
                        .HasColumnType("REAL");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.Property<double>("volume")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("VolumeResults");
                });
#pragma warning restore 612, 618
        }
    }
}
